node_name: "python-scanner-001"
version: "1.7.0"
max_task_num: 1
debug: false

redis:
  host: "10.33.155.74"
  port: 6379
  password: "0218eb100fee4fbcb90194070b77ab38"

mongodb:
  host: "10.33.155.74"
  port: 27017
  username: "root"
  password: "0218eb100fee4fbcb90194070b77ab38"
  database: "ScopeSentry" 